version: "3.7"

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: camunda
      POSTGRES_PASSWORD: camunda666
      POSTGRES_DB: camunda
    ports:
      - 5432:5432

#  camunda:
#    image: camunda/camunda-bpm-platform:7.12.0
#
#    environment:
#      DB_DRIVER: "org.postgresql.Driver"
#      DB_URL: "jdbc:postgresql://db:5432/camunda"
#      DB_USERNAME: "camunda"
#      DB_PASSWORD: "camunda666"
#      WAIT_FOR: "db:5432"
#      JAVA_OPTS: "-Xmx1024m -XX:MaxMetaspaceSize=256m"
#    links:
#      - "db"
#
#  nginx:
#    image: nginx
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    command: [nginx-debug, '-g', 'daemon off;']
#    ports:
#      - 8080:80
#    restart: always
#    links:
#     - "camunda"
#
#  excamad:
#    image: kotovdenis/excamad:latest
#    ports:
#      - 8282:80